// Generated by SunsetPR. This verifies migration invariants without calling external APIs.
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const assertions = [
  {
    "path": ".env.example",
    "oldText": "gemini-2.5-flash",
    "newText": "gemini-3.5-flash"
  },
  {
    "path": "config/models.yaml",
    "oldText": "gemini-2.5-flash",
    "newText": "gemini-3.5-flash"
  },
  {
    "path": "src/anthropic.py",
    "oldText": "claude-3-5-sonnet-20241022",
    "newText": "claude-sonnet-4-6"
  },
  {
    "path": "src/gemini.ts",
    "oldText": "gemini-2.5-flash",
    "newText": "gemini-3.5-flash"
  },
  {
    "path": "src/openai.ts",
    "oldText": "gpt-5-chat-latest",
    "newText": "gpt-5.5"
  }
];

for (const migration of assertions) {
  test(`${migration.path}: replaces ${migration.oldText}`, async () => {
    const source = await readFile(new URL(`../${migration.path}`, import.meta.url), "utf8");
    assert.equal(source.includes(migration.oldText), false, "deprecated model ID remains");
    assert.equal(source.includes(migration.newText), true, "replacement model ID is missing");
  });
}
