// Generated by SunsetPR. This verifies migration invariants without calling external APIs.
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const assertions = [
  {
    "path": ".env.example",
    "line": 1,
    "kind": "model_id",
    "oldText": "gemini-2.5-flash",
    "newText": "gemini-3.5-flash"
  },
  {
    "path": "config/models.yaml",
    "line": 1,
    "kind": "model_id",
    "oldText": "gemini-2.5-flash",
    "newText": "gemini-3.5-flash"
  },
  {
    "path": "src/anthropic.py",
    "line": 7,
    "kind": "model_id",
    "oldText": "claude-3-5-sonnet-20241022",
    "newText": "claude-sonnet-4-6"
  },
  {
    "path": "src/gemini.ts",
    "line": 11,
    "kind": "model_id",
    "oldText": "gemini-2.5-flash",
    "newText": "gemini-3.5-flash"
  },
  {
    "path": "src/openai.ts",
    "line": 8,
    "kind": "model_id",
    "oldText": "gpt-5-chat-latest",
    "newText": "gpt-5.5"
  }
];
const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

for (const migration of assertions) {
  test(`${migration.path}:${migration.line ?? "*"} verifies ${migration.kind}`, async () => {
    const source = await readFile(path.join(repositoryRoot, migration.path), "utf8");
    const scopedSource =
      migration.line === null ? source : (source.split(/\r?\n/)[migration.line - 1] ?? "");
    assert.equal(
      scopedSource.includes(migration.oldText),
      false,
      "removed migration input remains at the edited location",
    );
    if (migration.newText) {
      assert.equal(
        scopedSource.includes(migration.newText),
        true,
        "replacement model ID is missing at the edited location",
      );
    }
  });
}
